### ISSUE TITLE
Identifying whether a rectangle has been rotated

### ISSUE THREAD

**Issue by cjcahala** [mak-it/bin_packing#1]
In a current project I am working on it would be extremely helpful if I could be able to tell if a box within a bin has been rotated to fit at its position within the bin. Is this something that could be possible with this project?

**Comment by 5andi5** [comment]
Currently this is no supported out of the box.
Still you can add some methods to Box class to enable this behavior:
```
class RotatableBox < BinPacking::Box
  def initialize(width, height)
    super
    @original_width = width
  end

  def rotated?
    if @width == @height
      false
    else
      @original_width == @height
    end
  end
end
```
